# .readthedocs.yml

version: 2

# Specify the build environment
# This section is required for the v2 config file.
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

# Specify how to install Python dependencies
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs