default_inputs:
  clean_workdir: True
  max_iterations: 5
  qfpoints_distance: 0.1
  kfpoints_factor: 2
  # To set for the NSCF step of the Wannier90 work chain
  # One can either use `nscf` mode or `bands` mode. For the `nscf` mode,
  # the `nosym` and `noinv` must be set to True to avoid pw.x automatically
  # adds more (symmetry-equivalent) kpoints to the user-specified kpoints.
  # For the `bands` mode, pw.x will use exactly what the user provided.
  # In addition, it seems epw.x has some problem when restarting from a
  # pw.x calculation with `nosym` and `noinv` set to True, therefore, we
  # switch to the `bands` mode.
  epw:
    metadata:
      options:
        withmpi: True
    parameters:
      INPUTEPW:
        degaussw: 0.025
        elph: True
        ep_coupling: True
        eps_acustic: 0.1
        temps: 300
        vme: 'dipole'
        use_ws: True

default_protocol: moderate
protocols:
  moderate:
    description: 'Protocol to perform a electron-phonon calculation at normal precision at moderate computational cost.'
  precise:
    description: 'Protocol to perform a electron-phonon calculation at high precision at higher computational cost.'
    qfpoints_distance: 0.08
    kfpoints_factor: 2
  fast:
    description: 'Protocol to perform a electron-phonon calculation at low precision at minimal computational cost for testing purposes.'
    qfpoints_distance: 0.2
    kfpoints_factor: 1